// ============================================================
// MOCK DATA — IsyaratHUB Prototype
// Semua data di sini adalah dummy untuk keperluan demo/prototipe
// Lokasi disesuaikan dengan konteks Surabaya
// ============================================================

// --- Data JBI Tersedia (untuk Dashboard Pengguna Teman Tuli) ---
export const MOCK_JBI = [
  {
    id: 1,
    name: "Budi Santoso",
    specialty: "Medis & Hukum",
    rating: 4.9,
    totalSessions: 124,
    distance: "1.2 km",
    available: true,
    avatar: "BS",
    location: "Wonokromo, Surabaya",
    price: "Rp 75.000 / jam",
    bio: "Berpengalaman 5 tahun mendampingi Teman Tuli di RS dr. Soetomo dan kantor pengadilan.",
    verifiedSince: "Maret 2025",
  },
  {
    id: 2,
    name: "Siti Rahma",
    specialty: "Edukasi & Umum",
    rating: 4.7,
    totalSessions: 88,
    distance: "2.5 km",
    available: true,
    avatar: "SR",
    location: "Rungkut, Surabaya",
    price: "Rp 60.000 / jam",
    bio: "Relawan aktif di komunitas tuli Surabaya. Spesialisasi pendampingan di lingkungan sekolah dan kampus.",
    verifiedSince: "Januari 2026",
  },
  {
    id: 3,
    name: "Agus Wijaya",
    specialty: "Pemerintahan & Bisnis",
    rating: 4.8,
    totalSessions: 57,
    distance: "3.1 km",
    available: false,
    avatar: "AW",
    location: "Gubeng, Surabaya",
    price: "Rp 80.000 / jam",
    bio: "Terlatih untuk pendampingan di kantor dinas, perbankan, dan pertemuan bisnis formal.",
    verifiedSince: "Juni 2025",
  },
  {
    id: 4,
    name: "Dewi Kusuma",
    specialty: "Sosial & Komunitas",
    rating: 4.6,
    totalSessions: 42,
    distance: "4.0 km",
    available: true,
    avatar: "DK",
    location: "Kenjeran, Surabaya",
    price: "Rp 55.000 / jam",
    bio: "Aktif mendampingi kegiatan sosial kemasyarakatan dan acara komunitas inklusif di Surabaya.",
    verifiedSince: "April 2026",
  },
];

// --- Permintaan Masuk (untuk Dashboard JBI) ---
export const INCOMING_REQUESTS = [
  {
    id: 1,
    name: "Anita Rahman",
    type: "Medis — Pemeriksaan Rutin",
    time: "10:30 WIB — Hari Ini",
    location: "RS dr. Soetomo, Surabaya",
    address: "Jl. Mayjend Prof. Dr. Moestopo No.6–8, Surabaya",
    distance: "2.1 km",
    avatar: "AR",
    mode: "Offline",
    estimatedDuration: "1–2 jam",
    estimatedEarnings: "Rp 67.500 – Rp 135.000",
  },
  {
    id: 2,
    name: "Rizki Fauzi",
    type: "Edukasi — Sidang Skripsi",
    time: "14:00 WIB — Hari Ini",
    location: "Universitas Airlangga, Surabaya",
    address: "Kampus B UNAIR, Jl. Dharmawangsa Dalam, Surabaya",
    distance: "3.5 km",
    avatar: "RF",
    mode: "Offline",
    estimatedDuration: "2–3 jam",
    estimatedEarnings: "Rp 135.000 – Rp 202.500",
  },
  {
    id: 3,
    name: "Dina Mariana",
    type: "Layanan Publik - Dukcapil",
    time: "15:30 WIB — Hari Ini",
    location: "Video Call (Google Meet)",
    address: "Online",
    distance: "0 km",
    avatar: "DM",
    mode: "Online",
    estimatedDuration: "1 jam",
    estimatedEarnings: "Rp 67.500",
  },
];

// --- Riwayat Sesi (untuk HistoryTab Pengguna) ---
export const MOCK_USER_HISTORY = [
  {
    id: "bk-001",
    jbiName: "Budi Santoso",
    jbiAvatar: "BS",
    type: "Medis",
    location: "RS dr. Soetomo, Surabaya",
    date: "20 September 2026",
    time: "09:00 – 11:00 WIB",
    duration: "2 Jam",
    total: "Rp 150.000",
    status: "completed",
    rating: 5,
  },
  {
    id: "bk-002",
    jbiName: "Siti Rahma",
    jbiAvatar: "SR",
    type: "Edukasi",
    location: "UNAIR, Surabaya",
    date: "15 September 2026",
    time: "13:00 – 15:30 WIB",
    duration: "2.5 Jam",
    total: "Rp 150.000",
    status: "completed",
    rating: 4,
  },
  {
    id: "bk-003",
    jbiName: "Agus Wijaya",
    jbiAvatar: "AW",
    type: "Pemerintahan",
    location: "Kantor Dinsos Surabaya",
    date: "10 September 2026",
    time: "08:30 – 10:00 WIB",
    duration: "1.5 Jam",
    total: "Rp 120.000",
    status: "cancelled",
    rating: null,
  },
  {
    id: "bk-004",
    jbiName: "Dewi Kusuma",
    jbiAvatar: "DK",
    type: "Sosial",
    location: "Balai RW Kenjeran, Surabaya",
    date: "5 September 2026",
    time: "16:00 – 17:00 WIB",
    duration: "1 Jam",
    total: "Rp 55.000",
    status: "completed",
    rating: 5,
  },
];

// --- Riwayat Sesi (untuk HistoryTab JBI) ---
export const MOCK_JBI_HISTORY = [
  {
    id: "ses-001",
    clientName: "Anita Rahman",
    clientAvatar: "AR",
    type: "Medis",
    location: "RS dr. Soetomo, Surabaya",
    date: "20 September 2026",
    duration: "2 Jam",
    earnings: "Rp 135.000", // 90% dari Rp 150.000
    status: "completed",
  },
  {
    id: "ses-002",
    clientName: "Bambang Irawan",
    clientAvatar: "BI",
    type: "Hukum",
    location: "Pengadilan Negeri Surabaya",
    date: "18 September 2026",
    duration: "3 Jam",
    earnings: "Rp 202.500", // 90% dari Rp 225.000
    status: "completed",
  },
  {
    id: "ses-003",
    clientName: "Citra Dewi",
    clientAvatar: "CD",
    type: "Edukasi",
    location: "SLB Karya Mulya, Wonokromo",
    date: "12 September 2026",
    duration: "1.5 Jam",
    earnings: "Rp 101.250",
    status: "completed",
  },
  {
    id: "ses-004",
    clientName: "Dani Saputra",
    clientAvatar: "DS",
    type: "Sosial",
    location: "Kantor Dinsos Surabaya",
    date: "8 September 2026",
    duration: "1 Jam",
    earnings: "Rp 67.500",
    status: "completed",
  },
];

// --- Data Profil JBI (untuk ProfileTab JBI) ---
export const MOCK_JBI_PROFILE = {
  name: "Budi Santoso",
  avatar: "BS",
  email: "budi.santoso@jbi.isyarathub.id",
  phone: "+62 812-3456-7890",
  location: "Wonokromo, Surabaya",
  specialty: "Medis, Hukum, dan Pemerintahan",
  ratePerHour: "Rp 75.000",
  totalSessions: 124,
  rating: 4.9,
  walletBalance: 506.250, // saldo dalam angka (Rupiah)
  certStatus: "verified",
  certName: "Sertifikat JBI Profesional",
  certNumber: "JBI/PRO/2024/004721",
  verifiedSince: "Maret 2025",
  reviews: [
    { from: "Anita Rahman", rating: 5, comment: "Sangat sabar dan profesional, sangat membantu saat di RS!" },
    { from: "Bambang Irawan", rating: 5, comment: "Komunikasinya jelas dan tepat waktu." },
    { from: "Citra Dewi", rating: 4, comment: "Ramah dan mudah dipahami. Terima kasih banyak." },
  ],
};

// --- Notifikasi (untuk NotificationTab Pengguna) ---
export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    type: "booking_accepted",
    title: "Pesanan Diterima!",
    message: "Budi Santoso telah menerima permintaan Anda dan sedang menuju RS dr. Soetomo.",
    time: "2 menit yang lalu",
    isRead: false,
  },
  {
    id: 2,
    type: "rating_reminder",
    title: "Beri Ulasan untuk Siti Rahma",
    message: "Bagaimana sesi pendampingan Anda kemarin? Ulasan Anda membantu JBI lain berkembang.",
    time: "1 hari yang lalu",
    isRead: false,
  },
  {
    id: 3,
    type: "session_completed",
    title: "Sesi Selesai",
    message: "Sesi pendampingan bersama Agus Wijaya di Kantor Dinsos Surabaya telah selesai. Total: Rp 120.000.",
    time: "17 September 2026",
    isRead: true,
  },
  {
    id: 4,
    type: "promo",
    title: "Selamat Datang di IsyaratHUB!",
    message: "Akun Anda telah aktif. Mulai cari JBI terdekat sekarang dan rasakan kemudahan komunikasi inklusif.",
    time: "5 September 2026",
    isRead: true,
  },
];
